main:
  - name: About
    url: '#about'
    weight: 1 
  - name: Research
    url: /research/
    weight: 2 
  - name: Working Papers
    url: /working/
    weight: 3
  - name: Teaching
    url: /teaching/
    weight: 4  
  - name: CV
    url: /cv/
    weight: 5  